### ISSUE TITLE
Outreach or Sprint Review invite for NRM people? 

### ISSUE THREAD

**Issue by webgismd** [bcgov/moh-keycloak-user-management#66]
Hi Team! I am super interested and have been watching this repo for a while. 
Is there a possibility to extend an invite to one of your Sprint Reviews ...or alternatively I could set up an outreach meeting with interested people from IIT/NRM and DataBC? Thank you!

**Comment by sharpedavid** [comment]
Hi Michelle, I passed this on to my project manager Nicholas McCue. He should be in touch with you soon (and Steve?), but please let me know if he isn't.

(In my opinion, a Sprint Review won't be the best place for a discussion regarding this, because the "User Management Console" in this repo is a small fraction of the project team's work. Some sprints go by where we don't even touched the Console.)

**Comment by webgismd** [comment]
Thank-you @sharpedavid !

**Comment by sharpedavid** [comment]
@webgismd I'm following up with my team today.
